import { existsSync, mkdirSync, readFileSync, unlinkSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { claudeDir } from './watcher/paths'
import { HAMSTER_HOME } from './statusline'
import { ARCHITECT_AGENT } from './shell-wrapper'

/**
 * Collaboration mode ("협업 모드"), one switch:
 *   - the main interactive session keeps the user's model (e.g. Fable 5.1) and effort and acts as the
 *     architect: talks to the user, investigates, decides, writes specs, reviews;
 *   - every code change is delegated to the `hd-implementer` subagent, pinned to the `opus` alias
 *     (always the newest Opus) at the chosen effort (xhigh / max) or ultracode.
 * Implemented with Claude Code's own mechanisms: two agent files in ~/.claude/agents, plus one of
 * two ways of selecting the architect for the main session:
 *   - scope 'app' (default): the shells this app opens define a `claude` wrapper that adds
 *     `--agent hd-architect` (electron/shell-wrapper.ts). Only this app's terminals are affected,
 *     and the switch applies to the next `claude`, no restart needed.
 *   - scope 'global': the old behaviour — `agent` in ~/.claude/settings.json, which every claude on
 *     the machine picks up, including the user's own terminals.
 * Nothing runs outside the CLI, so speed and billing are untouched.
 */

export type ImplEffort = 'xhigh' | 'max' | 'ultracode'
/** 'app' = only the terminals this window opens; 'global' = settings.json, every claude session. */
export type HarnessScope = 'app' | 'global'

export interface HarnessConfig {
  implEffort: ImplEffort
  scope: HarnessScope
  on: boolean
}

export interface HarnessState {
  on: boolean
  config: HarnessConfig
  /** settings.json currently names a different agent (we would replace it and restore on disable) */
  foreignAgent: string | null
}

const ARCHITECT = ARCHITECT_AGENT
const IMPLEMENTER = 'hd-implementer'
const CONFIG_PATH = join(HAMSTER_HOME, 'harness.json')
const MARK = 'generated by Hamster Desk collaboration mode'

function agentsDir(): string {
  return join(claudeDir(), 'agents')
}
function settingsPath(): string {
  return join(claudeDir(), 'settings.json')
}
function readSettings(): Record<string, unknown> {
  try {
    return JSON.parse(readFileSync(settingsPath(), 'utf8')) as Record<string, unknown>
  } catch {
    return {}
  }
}
function writeSettings(s: Record<string, unknown>): void {
  writeFileSync(settingsPath(), JSON.stringify(s, null, 2) + '\n', 'utf8')
}

function rawHarnessConfig(): Partial<HarnessConfig> {
  try {
    return JSON.parse(readFileSync(CONFIG_PATH, 'utf8')) as Partial<HarnessConfig>
  } catch {
    return {}
  }
}

export function readHarnessConfig(): HarnessConfig {
  const j = rawHarnessConfig()
  return {
    implEffort: j.implEffort === 'xhigh' || j.implEffort === 'ultracode' ? j.implEffort : 'max',
    scope: j.scope === 'global' ? 'global' : 'app',
    on: j.on === true,
  }
}

function writeHarnessConfig(c: HarnessConfig): void {
  mkdirSync(HAMSTER_HOME, { recursive: true })
  writeFileSync(CONFIG_PATH, JSON.stringify(c, null, 2), 'utf8')
}

/** Store the settings we will restore on disable, then point settings.json at the architect. */
function claimGlobalAgent(): void {
  const s = readSettings()
  if (s.agent === ARCHITECT) return
  if (typeof s.agent === 'string') s.hamsterDeskPreviousAgent = s.agent
  s.agent = ARCHITECT
  writeSettings(s)
}

/** Undo claimGlobalAgent — only ever touches `agent` (and our own bookkeeping key). */
function releaseGlobalAgent(): void {
  const s = readSettings()
  if (s.agent !== ARCHITECT) return
  if (typeof s.hamsterDeskPreviousAgent === 'string') {
    s.agent = s.hamsterDeskPreviousAgent
    delete s.hamsterDeskPreviousAgent
  } else {
    delete s.agent
  }
  writeSettings(s)
}

/** Persist the config without flipping the switch (the ⋯ popover changes effort/scope while off). */
export function saveHarnessConfig(c: Partial<HarnessConfig>): HarnessState {
  const cur = readHarnessConfig()
  writeHarnessConfig({ ...cur, ...c, on: cur.on })
  return harnessState()
}

/**
 * Users of the first version had `agent: hd-architect` written into ~/.claude/settings.json, which
 * also caught every claude outside the app. Move them to the per-app wrapper once: keep the mode on,
 * but hand the global key back. Only `agent` (and our own marker) is touched.
 */
export function migrateHarness(): boolean {
  const raw = rawHarnessConfig()
  if (raw.scope !== undefined) return false
  const s = readSettings()
  if (s.agent !== ARCHITECT) return false
  writeHarnessConfig({ ...readHarnessConfig(), scope: 'app', on: true })
  releaseGlobalAgent()
  return true
}

function implementerMd(c: HarnessConfig): string {
  const effortLine = c.implEffort === 'ultracode' ? 'effort: max' : `effort: ${c.implEffort}`
  const ultracode = c.implEffort === 'ultracode'
  return `---
name: ${IMPLEMENTER}
description: 협업 모드의 구현 담당(Opus 최신, 최고 강도). 소스 코드를 실제로 만들거나 고치는 모든 작업 — 기능 구현, 버그 수정, 리팩터, 테스트·빌드 실행과 통과시키기 — 에 반드시 사용한다. 설계 담당이 명세를 넘기면 끝까지 구현하고 검증 결과와 바뀐 파일 목록을 보고한다.
model: opus
${effortLine}
---
<!-- ${MARK} -->
너는 협업 모드의 **구현 담당 엔지니어**다. 설계 담당(메인 세션)이 넘긴 명세를 정확히, 끝까지 구현한다.

원칙
- 명세에 적힌 파일·함수·동작·검수 기준을 그대로 따른다. 명세가 서로 모순되거나 결정적으로 빠진 정보가 있을 때만 구현을 멈추고 무엇이 필요한지 짧게 되묻는다. 사소한 판단은 스스로 내리고 보고에 적는다.
- 코드 스타일과 구조는 기존 코드베이스를 따른다. 불필요한 리팩터·범위 확장은 하지 않는다.
- 구현 후 반드시 검증한다: 타입 검사, 테스트, 빌드, 필요하면 실행. 실패하면 고치고 다시 검증한다.
- 보고는 짧고 구체적으로: 바꾼 파일 목록(경로), 무엇을 어떻게 바꿨는지 한 줄씩, 검증 명령과 결과, 남은 문제.
${ultracode ? '- 작업이 서로 독립적인 여러 부분으로 나뉘면 ultracode 로 병렬 처리한다.\n' : ''}`
}

function architectMd(c: HarnessConfig): string {
  return `---
name: ${ARCHITECT}
description: 협업 모드의 설계 담당(메인 세션). 사용자와 대화하고 조사·설계·검토를 맡으며, 코드 변경은 ${IMPLEMENTER} 에게 위임한다.
model: inherit
disallowedTools: Edit, Write, MultiEdit, NotebookEdit
---
<!-- ${MARK} -->
너는 협업 모드의 **설계 담당(아키텍트)** 이다. 사용자와 직접 대화하는 것은 너다.

역할 분담
- 너: 요구 파악, 코드베이스 조사(Read/Grep/Glob 등 읽기 도구), 설계 결정, 구현 명세 작성, 결과 검토, 사용자 보고.
- \`${IMPLEMENTER}\` 서브에이전트(Agent 도구, subagent_type: "${IMPLEMENTER}"; Opus 최신, effort ${c.implEffort}): 소스 코드를 만들거나 고치는 **모든** 작업. 너는 Edit/Write 도구가 없으므로 코드 변경은 반드시 위임한다. Bash 로 파일을 써서 우회하지 않는다.

진행 방식
1. 요청을 이해하고 필요한 만큼 코드를 읽어 설계를 정한다. 사용자의 판단이 정말 필요한 갈림길만 묻는다.
2. 관련된 변경은 하나의 위임으로 묶어 **완전한 명세**를 넘긴다: 목적, 바꿀 파일과 함수, 정확한 동작, 엣지 케이스, 검수 기준(어떤 명령이 통과해야 하는지). 독립적인 큰 덩어리는 여러 구현 담당을 병렬로 띄운다.
3. 돌아온 보고를 읽고 검토한다. 명세와 다르거나 검증이 빠졌으면 같은 구현 담당에게 다시 지시한다.
4. 사용자에게는 결과·바뀐 파일·검증 결과·남은 일을 짧게 보고한다.

코드 변경이 필요 없는 요청(질문, 설명, 조사, 계획)은 네가 직접 처리한다. 커밋·푸시는 사용자가 요청할 때만, 위임해서 한다.

기본 행동 규칙(이 프롬프트가 기본 시스템 프롬프트를 대체하므로 여기에 둔다)
- 사용자의 언어로 답한다(한국어면 한국어). 코드 식별자·명령·경로는 원문 그대로.
- 답은 결론부터, 짧게. 파일 참조는 \`path:line\` 형식. 명령·코드는 코드 블록에.
- 파일 검색·읽기는 Glob/Grep/Read 도구를 쓰고, Bash 는 실행·빌드·git 조회 같은 실제 명령에만 쓴다.
- 되돌리기 어렵거나 바깥에 영향이 가는 행동(삭제, 강제 푸시, 설정 변경, 외부 전송)은 먼저 확인을 받는다.
- 실패한 테스트·검증은 숨기지 않고 그대로 보고한다. 하지 않은 일을 했다고 하지 않는다.
- 프로젝트의 CLAUDE.md 와 메모리 지침을 따른다.
`
}

export function harnessState(): HarnessState {
  const s = readSettings()
  const agent = typeof s.agent === 'string' ? s.agent : null
  const config = readHarnessConfig()
  const filesOk = existsSync(join(agentsDir(), `${ARCHITECT}.md`)) && existsSync(join(agentsDir(), `${IMPLEMENTER}.md`))
  // scope 'app' needs nothing in settings.json — the shell wrapper reads harness.json directly.
  const on = config.on && filesOk && (config.scope === 'global' ? agent === ARCHITECT : true)
  return { on, config, foreignAgent: agent && agent !== ARCHITECT ? agent : null }
}

export function enableHarness(config: HarnessConfig): HarnessState {
  mkdirSync(agentsDir(), { recursive: true })
  writeFileSync(join(agentsDir(), `${IMPLEMENTER}.md`), implementerMd(config), 'utf8')
  writeFileSync(join(agentsDir(), `${ARCHITECT}.md`), architectMd(config), 'utf8')
  writeHarnessConfig({ ...config, on: true })
  if (config.scope === 'global') claimGlobalAgent()
  else releaseGlobalAgent() // switching global → app must not leave the key behind
  return harnessState()
}

export function disableHarness(): HarnessState {
  writeHarnessConfig({ ...readHarnessConfig(), on: false })
  releaseGlobalAgent()
  for (const n of [ARCHITECT, IMPLEMENTER]) {
    const p = join(agentsDir(), `${n}.md`)
    try {
      if (existsSync(p) && readFileSync(p, 'utf8').includes(MARK)) unlinkSync(p)
    } catch {
      /* ignore */
    }
  }
  return harnessState()
}
