import { existsSync, readFileSync, rmSync, unlinkSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { claudeDir } from './watcher/paths'
import { HAMSTER_HOME } from './statusline'

/**
 * One-shot cleanup of "collaboration mode", a feature this app used to have.
 *
 * It wrote two agent files into ~/.claude/agents and (in the first version) an `agent` key into
 * ~/.claude/settings.json, so every claude session — including ones started outside this app — came
 * up as hd-architect. That was the wrong shape: the app should not change how the user's CLI
 * behaves. The feature is gone; whether to use subagents is Claude Code's own call again.
 *
 * This removes what the app left behind, and only what the app itself wrote: an agent file is
 * deleted only when it still carries our marker, and settings.json is rewritten only when `agent`
 * is literally ours (restoring whatever was there before). Everything else is left alone, and any
 * error is swallowed — a leftover file is not worth failing startup over.
 */

const MARK = 'generated by Hamster Desk collaboration mode'
const AGENTS = ['hd-architect', 'hd-implementer']

export function cleanupLegacyHarness(): string[] {
  const removed: string[] = []

  for (const name of AGENTS) {
    const p = join(claudeDir(), 'agents', `${name}.md`)
    try {
      if (existsSync(p) && readFileSync(p, 'utf8').includes(MARK)) {
        unlinkSync(p)
        removed.push(`agents/${name}.md`)
      }
    } catch {
      /* not ours to worry about */
    }
  }

  try {
    const p = join(claudeDir(), 'settings.json')
    const s = JSON.parse(readFileSync(p, 'utf8')) as Record<string, unknown>
    const ours = s.agent === 'hd-architect'
    const hadPrevious = typeof s.hamsterDeskPreviousAgent === 'string'
    if (ours || hadPrevious) {
      if (ours) {
        if (hadPrevious) s.agent = s.hamsterDeskPreviousAgent
        else delete s.agent
      }
      delete s.hamsterDeskPreviousAgent
      writeFileSync(p, JSON.stringify(s, null, 2) + '\n', 'utf8')
      removed.push('settings.json agent')
    }
  } catch {
    /* no settings.json, or not JSON: nothing to undo */
  }

  for (const [label, p] of [
    ['harness.json', join(HAMSTER_HOME, 'harness.json')],
    ['shell/', join(HAMSTER_HOME, 'shell')],
  ] as const) {
    try {
      if (existsSync(p)) {
        rmSync(p, { recursive: true, force: true })
        removed.push(label)
      }
    } catch {
      /* ignore */
    }
  }

  return removed
}
