/**
 * The `claude` wrapper the app defines inside the shells it spawns.
 *
 * Collaboration mode used to set `agent` in ~/.claude/settings.json, which is global: *every*
 * claude on the machine came up as hd-architect, including sessions in the user's own terminals.
 * Instead the app now defines a `claude` shell function in the terminals it opens, and that function
 * decides — at call time — whether to prepend `--agent hd-architect`. Nothing outside this app is
 * affected, and toggling the switch takes effect on the next `claude`, with no terminal restart.
 *
 * The function reads $HAMSTER_HARNESS_FILE (set by spawnPty) on every call and injects only when
 * `on` is true and `scope` is not 'global'. It never injects for:
 *   - a CLI subcommand (`claude update`, `claude mcp …`): those take no --agent,
 *   - an explicit `--agent` from the user,
 *   - `-p` / `--print`: headless one-shots (the bubble summarizer's own calls look like this).
 * A missing or corrupt config file simply means "no injection".
 *
 * Pure strings, no Node APIs: scripts/harness-smoke.ts runs these under a real shell.
 */

export const ARCHITECT_AGENT = 'hd-architect'

/** Subcommands of the CLI; `claude <sub>` is not a session, so --agent would be wrong (or rejected). */
export const CLI_SUBCOMMANDS = [
  'update',
  'doctor',
  'mcp',
  'plugin',
  'auth',
  'config',
  'agents',
  'install',
  'setup-token',
  'attach',
  'logs',
  'stop',
  'rm',
  'migrate-installer',
]

/**
 * PowerShell (pwsh.exe / powershell.exe). Passed with -EncodedCommand so no script file has to exist
 * and no execution policy applies; -NoExit keeps the session interactive afterwards.
 * `Get-Command -CommandType Application` deliberately skips our own function and finds the real exe.
 */
export function psWrapperScript(): string {
  const subs = CLI_SUBCOMMANDS.map((s) => `'${s}'`).join(',')
  return `function global:claude {
  $hdExe = (Get-Command claude -CommandType Application -ErrorAction SilentlyContinue | Select-Object -First 1).Source
  if (-not $hdExe) { Write-Host 'claude 를 PATH 에서 찾을 수 없어요.' -ForegroundColor Red; return }
  $hdInject = $false
  $hdFile = $env:HAMSTER_HARNESS_FILE
  if ($hdFile -and (Test-Path -LiteralPath $hdFile)) {
    try {
      $hdCfg = Get-Content -LiteralPath $hdFile -Raw -ErrorAction Stop | ConvertFrom-Json
      if ($hdCfg.on -eq $true -and $hdCfg.scope -ne 'global') { $hdInject = $true }
    } catch { $hdInject = $false }
  }
  if ($hdInject -and $args.Count -gt 0) {
    $hdSubs = @(${subs})
    if ($hdSubs -contains [string]$args[0]) { $hdInject = $false }
    else { foreach ($hdA in $args) { if ($hdA -eq '--agent' -or $hdA -eq '-p' -or $hdA -eq '--print') { $hdInject = $false; break } } }
  }
  if ($hdInject) { & $hdExe --agent ${ARCHITECT_AGENT} @args } else { & $hdExe @args }
}`
}

/** UTF-16LE base64, which is what PowerShell's -EncodedCommand expects. */
export function encodeForPowerShell(script: string): string {
  return Buffer.from(script, 'utf16le').toString('base64')
}

/**
 * bash rc file (`bash --rcfile <path>`): sources the user's own ~/.bashrc first so the terminal still
 * looks like theirs, then defines the same wrapper. `type -P` finds the executable, never the function.
 * The config is read with grep because jq may not be installed.
 */
export function bashWrapperScript(): string {
  const subs = CLI_SUBCOMMANDS.join('|')
  return `# generated by Hamster Desk — claude wrapper for collaboration mode
[ -f "$HOME/.bashrc" ] && . "$HOME/.bashrc"

claude() {
  local hd_exe hd_inject hd_a
  hd_exe="$(command -v claude 2>/dev/null)"
  case "$hd_exe" in claude|'') hd_exe="$(type -P claude 2>/dev/null)";; esac
  if [ -z "$hd_exe" ]; then
    echo 'claude 를 PATH 에서 찾을 수 없어요.' >&2
    return 127
  fi
  hd_inject=0
  if [ -n "\${HAMSTER_HARNESS_FILE:-}" ] && [ -f "$HAMSTER_HARNESS_FILE" ]; then
    if grep -q '"on"[[:space:]]*:[[:space:]]*true' "$HAMSTER_HARNESS_FILE" 2>/dev/null &&
       ! grep -q '"scope"[[:space:]]*:[[:space:]]*"global"' "$HAMSTER_HARNESS_FILE" 2>/dev/null; then
      hd_inject=1
    fi
  fi
  if [ "$hd_inject" = 1 ] && [ $# -gt 0 ]; then
    case "$1" in ${subs}) hd_inject=0;; esac
    for hd_a in "$@"; do
      case "$hd_a" in --agent|-p|--print) hd_inject=0; break;; esac
    done
  fi
  if [ "$hd_inject" = 1 ]; then
    "$hd_exe" --agent ${ARCHITECT_AGENT} "$@"
  else
    "$hd_exe" "$@"
  fi
}
`
}
